config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get 'about' => 'pages#about'

  resources 'articles'

  get 'signup', to: 'users#new'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  # post 'users', to: 'users#create'
  resources 'users', except: [:new]


  resources :categories, except: [:destroy]
end

app/models/article.rb
class Article < ActiveRecord::Base
    belongs_to :user
    has_many :article_categories
    has_many :categories, through: :article_categories
    validates :title, presence: true, length: {minimum: 3, maximum: 50}
    validates :description, presence: true, length: {minimum: 10, maximum:  300}
    validates :user_id, presence: true
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

    before_action :set_article, only: [:show, :edit, :update, :destroy]
    before_action :require_user, except: [:index, :show]
    before_action :require_same_user, only: [:edit, :update, :destroy]

    # index method is action used to display all the articles stored in database
    def index
        @articles = Article.paginate(page: params[:page], per_page: 5)
    end


    def new
        @article = Article.new
    end

    # create action handeled by new method i.e on every new form submission
    def create
        
        # render plain: params[:article].inspect
        @article = Article.new(article_params)
        @article.user = current_user
        if @article.save
            flash[:success] = "Article created successfully"
            redirect_to article_path(@article)
        else
            render 'new'
        end
    end


    # this method render the @article get from create and display it in view
    def show
    end

    # edit method is used to edit the article by handeling update action
    def edit
    end

    def update
        @article.user = current_user
        if @article.update(article_params)
            flash[:success] = "Article updated successfully"
            redirect_to article_path(@article)
        else
            render 'edit'
        end
    end


    def destroy
        if @article.destroy
            flash[:danger] = "Article destroyed successfully"
            redirect_to articles_path
        end
    end

    private

        def set_article
            @article = Article.find(params[:id])
        end

    # this article_params method whitelist the title and description and returns to create method
        def article_params
            params.require(:article).permit(:title, :description, category_ids: [])
        end

        def require_same_user
            if current_user != @article.user and !current_user.admin?
                flash[:danger] = "you can only edit or delete your own article"
                redirect_to root_path
            end
        end
end

app/views/articles/_article.html.erb
<% obj.each do |article|%>
                <div class="row">
                    <div class="col-xs-8 col-xs-offset-2">
                        <div class="well well-lg">
                            <div class="article-title font-raleway">
                                <%= link_to article.title , article_path(article) %>            
                            </div>
                            
                            <div class="article-body font-raleway col-light-black-1">
                                <%= truncate(article.description, length: 100) %>
                            </div>
                            <span>
                                <small>
                                    created by: <%= article.user.username if article.user %>,
                                    <%= time_ago_in_words(article.created_at)%> ago, 
                                    last updated: <%= time_ago_in_words(article.updated_at)%> ago
                                </small>
                            </span>
                                <% if article.categories.any? %>
                                    <p class="font-raleway">Categories :  <%= render article.categories %> </p>
                                <%end%>
                            <% if logged_in? && (current_user == article.user || current_user.admin?) %>
                                <div class="article-actions">
                                    <%= link_to 'edit', edit_article_path(article), class: "btn btn-xs btn-info font-roboto" %>
                                    <%= link_to 'delete', article_path(article), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-xs btn-danger font-roboto" %>            
                                </div>
                            <%end%>
                        </div>
                    </div>
                </div>
                <%end%>

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article%>

<div class="form-container" >
    <%= form_for(@article, :html=>{class: "form-horizontal", role: "form"}) do |f|  %>
        <div class="form-group">
            <%= f.label :title, class: "col-sm-2 control-label" %>
            <div class="col-sm-7">
                <%= f.text_field :title, class: "form-control" %>
            </div>
        </div>
        
        <div class="form-group">
            <%= f.label :description, class: "col-sm-2 control-label" %> 
            <div class="col-sm-7">
                <%= f.text_area :description, class: "form-control" %>
            </div>
        </div>
        
        <div class="form-group">
            <%= f.label :category, class: "col-sm-2 control-label"%>
            <div class="col-sm-7 select-category-box">
                <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
                    <%= cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class: "checkbox") + cb.text}%>
                <%end%>
            </div>
        </div>


        <div class="form-group">
            <div class="col-sm-7 col-sm-offset-2">
                <%= f.submit class: "btn btn-primary"%>
            </div>
        </div>
    <%end%>
</div>
<br/>

app/views/articles/edit.html.erb
<div style="display: block; margin: 50px auto !important; width: 66%; color: #337ab7;"><h1 style="margin-top: 50px">Edit Article: </h1></div>

<%= render 'form' %>

<div style="display: block; margin: 15px auto !important; width: 66%; color: #337ab7;">[<%= link_to 'cancel request & back to articles', articles_path %>]</div>

app/views/articles/index.html.erb
<h1 class="center">Listing all Articles: </h1>




<% if @articles.length > 0 %>
    <div class="container">
        <div class="center"><%= will_paginate %></div>
        <%=  render "article", obj: @articles %>
    </div>
<%else%>
    <p>There is no Article..! would you like to <%= link_to 'create new article', new_article_path %></p>
<%end%>

app/views/articles/new.html.erb
<div style="display: block; margin: 0 auto !important; width: 66%; color: #337ab7;"><h1 style="margin-top: 50px;">Create new Article</h1></div>


<%= render 'form' %>
<div style="display: block; margin: 15px auto !important; width: 66%; color: #337ab7;"><%= link_to 'back to articles', articles_path %></div>

app/views/articles/show.html.erb
<!-- <h1>Article: </h1> -->

<h2 class="center font-raleway show-article-title"><strong>Title : </strong><%= @article.title %></h2>
    

<div class="well col-xs-8 col-xs-offset-2">
    <% if @article.user %>
        <div class="center">
        <ul><p class="font-weight-500 font-roboto col-light-black-2">Created by: </p>
            <li><%= link_to gravatar_for(@article.user), user_path(@article.user) %><br/>
            <span class="username-title font-raleway"><%= link_to @article.user.username, user_path(@article.user) %></span><br/>
            <span class="user-articles-count font-roboto font-weight-400 col-light-black-3"><%= pluralize(@article.user.articles.count, "article")%></span>
            </li>
        </ul>
        </div>
    <%end%>

    <p class="font-roboto"> <strong>Description : </strong> <div class="well col-light-black-3 font-raleway font-weight-500"><%= simple_format(@article.description) %></div></p>

    <% if @article.categories.any? %>
        <p class="font-raleway">Categories :  <%= render @article.categories %> </p>
    <%end%>
    <div style="margin: 30px 0 10px 0;">
        <%= link_to 'back to articles', articles_path, class: "btn btn-xs btn-primary font-raleway font-weight-500" %>
        <% if logged_in? && (current_user == @article.user || current_user.admin? ) %>
            <%= link_to 'edit this article', edit_article_path(@article), class: "btn btn-xs btn-info font-raleway font-weight-500"%>
        <%end%>
    </div>
</div>