config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get 'about' => 'pages#about'

  resources 'articles'

  get 'signup', to: 'users#new'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  # post 'users', to: 'users#create'
  resources 'users', except: [:new]


  resources :categories, except: [:destroy]
end

app/models/category.rb
class Category < ActiveRecord::Base
    has_many :article_categories
    has_many :articles, through: :article_categories
    validates :name, presence: true, uniqueness: true, length: {minimum: 3, maximum: 25}
    # validates_uniqueness_of :name
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    before_action :require_admin, only: [:new, :create, :edit]
    def index
        @categories = Category.paginate(page: params[:page], per_page: 10)
    end

    def new
        @category = Category.new
    end

    def show
        @category = Category.find(params[:id])
        @category_articles = @category.articles.paginate(page: params[:page], per_page: 5)
    end

    def create
        @category = Category.new(category_params)
        if @category.save
            flash[:success] = " #{@category.name} category created successfully."
            redirect_to categories_path
        else
            render 'new'
        end
    end

    def edit

        @category = Category.find(params[:id])
    end

    def update
        @category = Category.find(params[:id])
        if @category.update(category_params)
            flash[:success] = "Category name was successfuly updated"
            redirect_to category_path(@category)
        else
            render 'edit'
        end
    end

    private
    def category_params
        params.require(:category).permit(:name)
    end

    def require_admin
        if !logged_in? || (logged_in? and  !current_user.admin?)
            flash[:danger] = "only admin's can perform this action"
            redirect_to categories_path
        end
    end
end

app/views/categories/_category.html.erb
<span class="badge"><%= link_to category.name.capitalize, category_path(category) %></span>

app/views/categories/_form.html.erb
<div class="row">
    <div class="col-xs-12">
        <div class="form-container" >
            <%= form_for(@category, :html=>{class: "form-horizontal", role: "form"}) do |f|  %>
                <div class="form-group">
                    <%= f.label :name, class: "col-sm-2 control-label" %>
                    <div class="col-sm-7">
                        <%= f.text_field :name, class: "form-control", placeholder: "Enter category name", autofocus: true %>
                    </div>
                </div>
                
                <div class="form-group">
                    <div class="col-sm-7 col-sm-offset-2">
                        <%= f.submit class: "btn btn-primary" %>
                    </div>
                </div>
            <%end%>
        </div>
    </div>
</div>

app/views/categories/edit.html.erb
<h1 class="center">Edit Category name: </h1>

<%=  render 'form' %>

app/views/categories/index.html.erb
<h1 class="center">listing all categories</h1>
<div class="main-container">
    <div class="center"><%= will_paginate %></div>
    <ul>
        <% @categories.each do |category| %>
            <div class="row">
                <div class="col-md-4 col-md-offset-4">
                    <div class="well">
                        <div class="article-body font-roboto font-weight-800">
                            <div class="category-box">
                                <li><%= link_to category.name.capitalize , category_path(category) %></li>
                                <li><small><%= pluralize(category.articles.count, "article") %></small></li>
                            </div>          
                        </div>
                    </div>
                </div>
            </div>
        <%end%>
    </ul>    
    <div class="center"><%= will_paginate %></div>
</div>

app/views/categories/new.html.erb
<h1 class="center">Create new category</h1>
<%= render 'shared/errors', obj: @category %>


<%= render 'form'%>

app/views/categories/show.html.erb
<h1 class="center"><%= "Category: "+ @category.name %> 
    <% if logged_in? and current_user.admin? %>
        <span class="edit-category-link">
            <sup><%= link_to "edit", edit_category_path(@category) %></sup>
        </span>
    <%end%>
</h1>




<% if @category_articles.length > 0 %>
    <div class="container">
        <div class="center"><%= will_paginate @category_articles %></div>
        <%=  render "articles/article", obj: @category_articles %>
        <div class="center"><%= will_paginate @category_articles %></div>
    </div>
<%else%>
    <div class="row">
        <div class="well well-lg">
            <p>There is no Article..! would you like to <%= link_to 'create new article', new_article_path %></p>
        </div>
    </div>
<%end%>