config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get 'about' => 'pages#about'

  resources 'articles'

  get 'signup', to: 'users#new'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  # post 'users', to: 'users#create'
  resources 'users', except: [:new]


  resources :categories, except: [:destroy]
end

app/views/layouts/_footer.html.erb
<!-- <div class="container"> -->
<div class="footer-container">
    <footer class="pre-footer"></footer>
    <footer class="main-footer">
        <small>copyright &copy; <a href="http://ideobyte.com" target="_blank">ideobyte developer</a></small>
        <nav>
            <ul>
                <li><%= link_to 'About us', about_path %></li>
            </ul>
        </nav>
    </footer>
    <footer class="post-footer"></footer>
</div>    
<!-- </div> -->

app/views/layouts/_messages.html.erb
<div class="row" style=" margin-top: 100px">
    <div class="col-xs-10 col-xs-offset-1">
        <% flash.each do |name,msg| %>    
            <div class='alert alert-<%= "#{name}" %>'>
                <a href="#" class="close" data-dismiss="alert" >&#215;</a>
                <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
            </div>
        <%end%>
    </div> 
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'iBlog', root_path, class: "navbar-brand", id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse custom-navbar" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Articles', articles_path %></li>
        <li><%= link_to 'Users', users_path %></li>
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Actions<span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to 'New Article', new_article_path %></li>
              <li><a href="#">Another action</a></li>
              <li><a href="#">Something else here</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">Separated link</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">One more separated link</a></li>
            </ul>
          </li>
        <%end%>
      </ul>

      <ul class="nav navbar-nav">
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Categories<span class="caret"></span></a>
            <ul class="dropdown-menu category-dropdown">
              <li role="separator" class="divider"></li>
              <li><%= link_to 'All categories', categories_path %></li>
              <li role="separator" class="divider"></li>
              <div class="category-limit-view">
                <% Category.all.each do |category| %>
                  <li><%= link_to "#{category.name}", category_path(category) %></li>
                <%end%>
              </div>
              <li role="separator" class="divider"></li>
              <% if logged_in? and current_user.admin? %>
                <li><%= link_to "create new category",  new_category_path %></li>
                <li role="separator" class="divider"></li>
              <%end%>

            </ul>
          </li>
        <%end%>
      </ul>

      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
          <% if logged_in? %>
                <li><%= link_to 'Logout', logout_path, method: :delete %></li>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">My Profile <%= "Admin" if current_user.admin? %><span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <li><%= link_to 'Edit my profile', edit_user_path(current_user) %></li>
                    <li><%= link_to 'View my Profile', user_path(current_user) %></li>
                    <li><a href="#">Something else here</a></li>
                    <li role="separator" class="divider"></li>
                    <li><a href="#">Separated link</a></li>
                  </ul>
                </li>
          <%else%>
                <li><%= link_to 'Login', login_path %></li>
                <li><%= link_to 'Signup', signup_path %></li>
          <%end%>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>iBlog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href='https://fonts.googleapis.com/css?family=Raleway:200,300,400,500,600,700,800,900' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,900' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Oswald:200,300,400,500,600,700' rel='stylesheet' type='text/css'>
  </head>

  <body>
        <%= render 'layouts/navigation'%>
        <%= render 'layouts/messages'%>
        <div class="container">
        <%= yield %>
        </div>
        <%= render 'layouts/footer' %>
  </body>
</html>